services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver2022
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "a123456!"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql-data:/var/opt/mssql
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mssql-data:
  mongo-data: